#!/usr/bin/env ruby
# build_audio.rb — generate per-post TTS narration MP3s.
#
# Engine: Piper (https://github.com/rhasspy/piper). Self-hosted,
# free, runs in CI without secrets. The script:
#
#   1. Walks `_posts/*.md`, strips frontmatter and markdown to plain
#      prose suitable for narration.
#   2. Hashes the prose with sha256; if `_data/audio.yml` already
#      records that hash for the slug *and* the MP3 exists, skips
#      regeneration.
#   3. Pipes the prose through `piper` and `ffmpeg` (mp3 encode) when
#      both are on PATH. Writes `audio/<slug>.mp3`.
#   4. Updates `_data/audio.yml` with the manifest the post layout
#      and podcast feeds read (`url`, `hash`, `bytes`, `duration`,
#      `generated_at`).
#
# When piper or ffmpeg is missing the script logs once and skips
# generation, but still emits the manifest based on previously-
# generated files. This keeps local Jekyll builds working without
# the TTS toolchain installed (a fresh clone simply has no audio).
#
# Embargoed posts and posts with `audio_override:` are deliberately
# skipped: an override is the author's hand-recorded edition, and an
# embargoed post must not leak via narration.
#
# Environment:
#   PIPER_BIN      — path to the piper executable (default: `piper`)
#   PIPER_VOICE    — path to the .onnx voice model (required)
#   FFMPEG_BIN     — path to ffmpeg (default: `ffmpeg`)

require 'digest'
require 'fileutils'
require 'open3'
require 'tmpdir'
require 'yaml'
require 'time'
require 'date'

ROOT        = File.expand_path('..', __dir__)
POSTS_DIR   = File.join(ROOT, '_posts')
AUDIO_DIR   = File.join(ROOT, 'audio')
DATA_PATH   = File.join(ROOT, '_data', 'audio.yml')
PIPER       = ENV['PIPER_BIN']  || 'piper'
PIPER_VOICE = ENV['PIPER_VOICE']
FFMPEG      = ENV['FFMPEG_BIN'] || 'ffmpeg'

HEADER = <<~HEAD
  # _data/audio.yml — build-time TTS narration manifest.
  #
  # Generated by scripts/build_audio.rb. Do not edit by hand.
  # Each entry maps a post slug to its narration:
  #   url            — relative path served by GitHub Pages
  #   hash           — sha256 of the prose used to render the audio
  #   bytes          — MP3 size; emitted into the podcast <enclosure>
  #   duration       — HH:MM:SS, emitted as <itunes:duration>
  #   generated_at   — ISO 8601 build-time stamp
  #
  # An empty manifest is the legitimate state on a fresh checkout — the
  # `audio.yml` workflow regenerates the file in CI when posts change.
HEAD

def have?(bin)
  Open3.capture3(bin, '--version')
  true
rescue Errno::ENOENT, StandardError
  false
end

def parse_post(path)
  body = File.read(path)
  return [nil, nil, nil] unless body.start_with?('---')
  fm_end = body.index("\n---", 3)
  return [nil, nil, nil] unless fm_end
  fm = YAML.safe_load(body[4..fm_end], permitted_classes: [Time, Date]) || {}
  prose = body[(fm_end + 4)..].to_s
  slug = File.basename(path).sub(/\A\d{4}-\d{2}-\d{2}-/, '').sub(/\.md\z/, '')
  [slug, fm, prose]
end

# Strip markdown to plain prose suitable for narration.
def to_plain(md)
  s = md.dup
  s.gsub!(/```.*?```/m, ' ')                # fenced code
  s.gsub!(/`[^`]+`/, ' ')                   # inline code
  s.gsub!(/^\[\^[^\]]+\]:[^\n]*\n?/, '')    # footnote definitions
  s.gsub!(/\[\^[^\]]+\]/, '')               # footnote refs
  s.gsub!(/<[^>]+>/, ' ')                   # html tags
  s.gsub!(/!\[([^\]]*)\]\([^)]+\)/, '\1')   # images
  s.gsub!(/\[([^\]]+)\]\([^)]+\)/, '\1')    # links
  s.gsub!(/^[#>\-\*]+\s*/, '')              # heading / blockquote / bullet markers
  s.gsub!(/[*_]{1,3}/, '')                  # emphasis markers
  s.gsub!(/\s+/, ' ')
  s.strip
end

def write_manifest(map)
  body = map.empty? ? "{}\n" : map.sort.to_h.to_yaml.sub("---\n", '')
  File.write(DATA_PATH, HEADER + body)
end

def existing_manifest
  return {} unless File.exist?(DATA_PATH)
  data = YAML.safe_load_file(DATA_PATH, permitted_classes: [Time, Date])
  data.is_a?(Hash) ? data : {}
end

def piper_missing_voice_error
  warn '[build_audio] PIPER_VOICE is not set; cannot synthesize.'
  warn '              Set PIPER_VOICE=/path/to/voice.onnx and re-run.'
end

def synthesize(slug, prose_plain)
  out_mp3 = File.join(AUDIO_DIR, "#{slug}.mp3")
  FileUtils.mkdir_p(AUDIO_DIR)
  tmp_wav = File.join(Dir.tmpdir, "oc-audio-#{slug}-#{$$}.wav")
  begin
    Open3.popen3(PIPER, '--model', PIPER_VOICE, '--output_file', tmp_wav) do |stdin, _stdout, _stderr, wait|
      stdin.write(prose_plain)
      stdin.close
      raise "piper failed for #{slug}" unless wait.value.success?
    end
    out, err, st = Open3.capture3(FFMPEG, '-y', '-i', tmp_wav,
                                  '-codec:a', 'libmp3lame', '-q:a', '4', out_mp3)
    raise "ffmpeg failed for #{slug}: #{err}" unless st.success?
    bytes = File.size(out_mp3)
    probe = Open3.capture3(FFMPEG, '-i', out_mp3).join
    duration = probe[/Duration: (\d{2}:\d{2}:\d{2})/, 1] || '00:00:00'
    [out_mp3, bytes, duration]
  ensure
    File.unlink(tmp_wav) if File.exist?(tmp_wav)
  end
end

# ---------------------------------------------------------------------------

existing = existing_manifest
piper_ok = have?(PIPER)
ff_ok    = have?(FFMPEG)

unless piper_ok && ff_ok
  warn "[build_audio] piper=#{piper_ok} ffmpeg=#{ff_ok} — skipping new generation; manifest reflects existing files only."
end

result = {}
generated = 0
skipped = 0

Dir[File.join(POSTS_DIR, '*.md')].sort.each do |path|
  slug, fm, prose = parse_post(path)
  next unless slug
  next if fm['audio_override']
  next if fm['embargo_until'] || fm['embargo_block']

  prose_plain = to_plain(prose)
  next if prose_plain.empty?
  digest = Digest::SHA256.hexdigest(prose_plain)
  out_mp3 = File.join(AUDIO_DIR, "#{slug}.mp3")
  rel_url = "/audio/#{slug}.mp3"

  prior = existing[slug]
  if prior && prior['hash'] == digest && File.exist?(out_mp3)
    result[slug] = prior
    skipped += 1
    next
  end

  unless piper_ok && ff_ok
    result[slug] = prior if prior  # keep what we have
    skipped += 1
    next
  end

  if PIPER_VOICE.nil? || PIPER_VOICE.empty?
    piper_missing_voice_error
    exit 2
  end

  begin
    _path, bytes, duration = synthesize(slug, prose_plain)
    result[slug] = {
      'url'          => rel_url,
      'hash'         => digest,
      'bytes'        => bytes,
      'duration'     => duration,
      'generated_at' => Time.now.utc.iso8601
    }
    generated += 1
    puts "[build_audio] generated #{rel_url} (#{bytes} bytes, #{duration})"
  rescue => e
    warn "[build_audio] failed for #{slug}: #{e.message}"
  end
end

write_manifest(result)
puts "[build_audio] manifest size=#{result.size}, generated=#{generated}, skipped=#{skipped}"
